/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_lang_invoke_LambdaProxyClassArchive */

#ifndef _Included_java_lang_invoke_LambdaProxyClassArchive
#define _Included_java_lang_invoke_LambdaProxyClassArchive
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_lang_invoke_LambdaProxyClassArchive
 * Method:    addToArchive
 * Signature: (Ljava/lang/Class;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MemberName;Ljava/lang/invoke/MethodType;Ljava/lang/Class;)V
 */
JNIEXPORT void JNICALL Java_java_lang_invoke_LambdaProxyClassArchive_addToArchive
  (JNIEnv *, jclass, jclass, jstring, jobject, jobject, jobject, jobject, jclass);

/*
 * Class:     java_lang_invoke_LambdaProxyClassArchive
 * Method:    findFromArchive
 * Signature: (Ljava/lang/Class;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MemberName;Ljava/lang/invoke/MethodType;)Ljava/lang/Class;
 */
JNIEXPORT jclass JNICALL Java_java_lang_invoke_LambdaProxyClassArchive_findFromArchive
  (JNIEnv *, jclass, jclass, jstring, jobject, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
