/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_lang_ref_PhantomReference */

#ifndef _Included_java_lang_ref_PhantomReference
#define _Included_java_lang_ref_PhantomReference
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_lang_ref_PhantomReference
 * Method:    refersTo0
 * Signature: (Ljava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_java_lang_ref_PhantomReference_refersTo0
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
