/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef $LL
#ifdef _WIN32
#define $LL(x) x##i64
#else
#define $LL(x) x##LL
#endif
#endif

/* Header for class java_util_concurrent_atomic_AtomicLong */

#ifndef _Included_java_util_concurrent_atomic_AtomicLong
#define _Included_java_util_concurrent_atomic_AtomicLong
#ifdef __cplusplus
extern "C" {
#endif
#undef java_util_concurrent_atomic_AtomicLong_serialVersionUID
#define java_util_concurrent_atomic_AtomicLong_serialVersionUID $LL(-8742448824652078965)
#undef java_util_concurrent_atomic_AtomicLong_serialVersionUID
#define java_util_concurrent_atomic_AtomicLong_serialVersionUID $LL(1927816293512124184)
/*
 * Class:     java_util_concurrent_atomic_AtomicLong
 * Method:    VMSupportsCS8
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_java_util_concurrent_atomic_AtomicLong_VMSupportsCS8
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
