/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef $LL
#ifdef _WIN32
#define $LL(x) x##i64
#else
#define $LL(x) x##LL
#endif
#endif

/* Header for class java_lang_NullPointerException */

#ifndef _Included_java_lang_NullPointerException
#define _Included_java_lang_NullPointerException
#ifdef __cplusplus
extern "C" {
#endif
#undef java_lang_NullPointerException_serialVersionUID
#define java_lang_NullPointerException_serialVersionUID $LL(-3042686055658047285)
#undef java_lang_NullPointerException_serialVersionUID
#define java_lang_NullPointerException_serialVersionUID $LL(-3387516993124229948)
#undef java_lang_NullPointerException_serialVersionUID
#define java_lang_NullPointerException_serialVersionUID $LL(-7034897190745766939)
#undef java_lang_NullPointerException_serialVersionUID
#define java_lang_NullPointerException_serialVersionUID $LL(5162710183389028792)
/*
 * Class:     java_lang_NullPointerException
 * Method:    getExtendedNPEMessage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_java_lang_NullPointerException_getExtendedNPEMessage
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
