/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_nio_MappedMemoryUtils */

#ifndef _Included_java_nio_MappedMemoryUtils
#define _Included_java_nio_MappedMemoryUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_nio_MappedMemoryUtils
 * Method:    isLoaded0
 * Signature: (JJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_java_nio_MappedMemoryUtils_isLoaded0
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     java_nio_MappedMemoryUtils
 * Method:    load0
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_java_nio_MappedMemoryUtils_load0
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     java_nio_MappedMemoryUtils
 * Method:    unload0
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_java_nio_MappedMemoryUtils_unload0
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     java_nio_MappedMemoryUtils
 * Method:    force0
 * Signature: (Ljava/io/FileDescriptor;JJ)V
 */
JNIEXPORT void JNICALL Java_java_nio_MappedMemoryUtils_force0
  (JNIEnv *, jclass, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
