/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef $LL
#ifdef _WIN32
#define $LL(x) x##i64
#else
#define $LL(x) x##LL
#endif
#endif

/* Header for class java_util_TimeZone */

#ifndef _Included_java_util_TimeZone
#define _Included_java_util_TimeZone
#ifdef __cplusplus
extern "C" {
#endif
#undef java_util_TimeZone_SHORT
#define java_util_TimeZone_SHORT 0L
#undef java_util_TimeZone_LONG
#define java_util_TimeZone_LONG 1L
#undef java_util_TimeZone_ONE_MINUTE
#define java_util_TimeZone_ONE_MINUTE 60000L
#undef java_util_TimeZone_ONE_HOUR
#define java_util_TimeZone_ONE_HOUR 3600000L
#undef java_util_TimeZone_ONE_DAY
#define java_util_TimeZone_ONE_DAY 86400000L
#undef java_util_TimeZone_serialVersionUID
#define java_util_TimeZone_serialVersionUID $LL(3581463369166924961)
#undef java_util_TimeZone_GMT_ID_LENGTH
#define java_util_TimeZone_GMT_ID_LENGTH 3L
/*
 * Class:     java_util_TimeZone
 * Method:    getSystemTimeZoneID
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_java_util_TimeZone_getSystemTimeZoneID
  (JNIEnv *, jclass, jstring);

/*
 * Class:     java_util_TimeZone
 * Method:    getSystemGMTOffsetID
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_java_util_TimeZone_getSystemGMTOffsetID
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
