/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef $LL
#ifdef _WIN32
#define $LL(x) x##i64
#else
#define $LL(x) x##LL
#endif
#endif

/* Header for class java_lang_Long */

#ifndef _Included_java_lang_Long
#define _Included_java_lang_Long
#ifdef __cplusplus
extern "C" {
#endif
#undef java_lang_Long_serialVersionUID
#define java_lang_Long_serialVersionUID $LL(-8742448824652078965)
#undef java_lang_Long_MIN_VALUE
#define java_lang_Long_MIN_VALUE $LL(-9223372036854775808)
#undef java_lang_Long_MAX_VALUE
#define java_lang_Long_MAX_VALUE $LL(9223372036854775807)
#undef java_lang_Long_SIZE
#define java_lang_Long_SIZE 64L
#undef java_lang_Long_BYTES
#define java_lang_Long_BYTES 8L
#undef java_lang_Long_serialVersionUID
#define java_lang_Long_serialVersionUID $LL(4290774380558885855)
#ifdef __cplusplus
}
#endif
#endif
