/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_security_AccessController */

#ifndef _Included_java_security_AccessController
#define _Included_java_security_AccessController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_security_AccessController
 * Method:    getProtectionDomain
 * Signature: (Ljava/lang/Class;)Ljava/security/ProtectionDomain;
 */
JNIEXPORT jobject JNICALL Java_java_security_AccessController_getProtectionDomain
  (JNIEnv *, jclass, jclass);

/*
 * Class:     java_security_AccessController
 * Method:    ensureMaterializedForStackWalk
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_java_security_AccessController_ensureMaterializedForStackWalk
  (JNIEnv *, jclass, jobject);

/*
 * Class:     java_security_AccessController
 * Method:    getStackAccessControlContext
 * Signature: ()Ljava/security/AccessControlContext;
 */
JNIEXPORT jobject JNICALL Java_java_security_AccessController_getStackAccessControlContext
  (JNIEnv *, jclass);

/*
 * Class:     java_security_AccessController
 * Method:    getInheritedAccessControlContext
 * Signature: ()Ljava/security/AccessControlContext;
 */
JNIEXPORT jobject JNICALL Java_java_security_AccessController_getInheritedAccessControlContext
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
