/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef $LL
#ifdef _WIN32
#define $LL(x) x##i64
#else
#define $LL(x) x##LL
#endif
#endif

/* Header for class java_lang_Integer */

#ifndef _Included_java_lang_Integer
#define _Included_java_lang_Integer
#ifdef __cplusplus
extern "C" {
#endif
#undef java_lang_Integer_serialVersionUID
#define java_lang_Integer_serialVersionUID $LL(-8742448824652078965)
#undef java_lang_Integer_MIN_VALUE
#define java_lang_Integer_MIN_VALUE -2147483648L
#undef java_lang_Integer_MAX_VALUE
#define java_lang_Integer_MAX_VALUE 2147483647L
#undef java_lang_Integer_SIZE
#define java_lang_Integer_SIZE 32L
#undef java_lang_Integer_BYTES
#define java_lang_Integer_BYTES 4L
#undef java_lang_Integer_serialVersionUID
#define java_lang_Integer_serialVersionUID $LL(1360826667806852920)
#ifdef __cplusplus
}
#endif
#endif
