/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_io_FileCleanable */

#ifndef _Included_java_io_FileCleanable
#define _Included_java_io_FileCleanable
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_io_FileCleanable
 * Method:    cleanupClose0
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_java_io_FileCleanable_cleanupClose0
  (JNIEnv *, jclass, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
