/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jdk_internal_misc_ScopedMemoryAccess */

#ifndef _Included_jdk_internal_misc_ScopedMemoryAccess
#define _Included_jdk_internal_misc_ScopedMemoryAccess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jdk_internal_misc_ScopedMemoryAccess
 * Method:    registerNatives
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jdk_internal_misc_ScopedMemoryAccess_registerNatives
  (JNIEnv *, jclass);

/*
 * Class:     jdk_internal_misc_ScopedMemoryAccess
 * Method:    closeScope0
 * Signature: (Ljdk/internal/misc/ScopedMemoryAccess/Scope;Ljdk/internal/misc/ScopedMemoryAccess/Scope/ScopedAccessError;)Z
 */
JNIEXPORT jboolean JNICALL Java_jdk_internal_misc_ScopedMemoryAccess_closeScope0
  (JNIEnv *, jobject, jobject, jthrowable);

#ifdef __cplusplus
}
#endif
#endif
