/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jdk_internal_loader_NativeLibraries */

#ifndef _Included_jdk_internal_loader_NativeLibraries
#define _Included_jdk_internal_loader_NativeLibraries
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jdk_internal_loader_NativeLibraries
 * Method:    load
 * Signature: (Ljdk/internal/loader/NativeLibraries/NativeLibraryImpl;Ljava/lang/String;ZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_jdk_internal_loader_NativeLibraries_load
  (JNIEnv *, jclass, jobject, jstring, jboolean, jboolean);

/*
 * Class:     jdk_internal_loader_NativeLibraries
 * Method:    unload
 * Signature: (Ljava/lang/String;ZZJ)V
 */
JNIEXPORT void JNICALL Java_jdk_internal_loader_NativeLibraries_unload
  (JNIEnv *, jclass, jstring, jboolean, jboolean, jlong);

/*
 * Class:     jdk_internal_loader_NativeLibraries
 * Method:    findBuiltinLib
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jdk_internal_loader_NativeLibraries_findBuiltinLib
  (JNIEnv *, jclass, jstring);

/*
 * Class:     jdk_internal_loader_NativeLibraries
 * Method:    findEntry0
 * Signature: (Ljdk/internal/loader/NativeLibraries/NativeLibraryImpl;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_jdk_internal_loader_NativeLibraries_findEntry0
  (JNIEnv *, jclass, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
