/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jdk_internal_misc_CDS */

#ifndef _Included_jdk_internal_misc_CDS
#define _Included_jdk_internal_misc_CDS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jdk_internal_misc_CDS
 * Method:    isDumpingClassList0
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jdk_internal_misc_CDS_isDumpingClassList0
  (JNIEnv *, jclass);

/*
 * Class:     jdk_internal_misc_CDS
 * Method:    isDumpingArchive0
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jdk_internal_misc_CDS_isDumpingArchive0
  (JNIEnv *, jclass);

/*
 * Class:     jdk_internal_misc_CDS
 * Method:    isSharingEnabled0
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jdk_internal_misc_CDS_isSharingEnabled0
  (JNIEnv *, jclass);

/*
 * Class:     jdk_internal_misc_CDS
 * Method:    logLambdaFormInvoker
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jdk_internal_misc_CDS_logLambdaFormInvoker
  (JNIEnv *, jclass, jstring);

/*
 * Class:     jdk_internal_misc_CDS
 * Method:    initializeFromArchive
 * Signature: (Ljava/lang/Class;)V
 */
JNIEXPORT void JNICALL Java_jdk_internal_misc_CDS_initializeFromArchive
  (JNIEnv *, jclass, jclass);

/*
 * Class:     jdk_internal_misc_CDS
 * Method:    defineArchivedModules
 * Signature: (Ljava/lang/ClassLoader;Ljava/lang/ClassLoader;)V
 */
JNIEXPORT void JNICALL Java_jdk_internal_misc_CDS_defineArchivedModules
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     jdk_internal_misc_CDS
 * Method:    getRandomSeedForDumping
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jdk_internal_misc_CDS_getRandomSeedForDumping
  (JNIEnv *, jclass);

/*
 * Class:     jdk_internal_misc_CDS
 * Method:    dumpClassList
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jdk_internal_misc_CDS_dumpClassList
  (JNIEnv *, jclass, jstring);

/*
 * Class:     jdk_internal_misc_CDS
 * Method:    dumpDynamicArchive
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jdk_internal_misc_CDS_dumpDynamicArchive
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
