/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jdk_internal_jimage_RuntimeImageReader */

#ifndef _Included_jdk_internal_jimage_RuntimeImageReader
#define _Included_jdk_internal_jimage_RuntimeImageReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jdk_internal_jimage_RuntimeImageReader
 * Method:    findLocation0
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljdk/internal/jimage/RuntimeImageLocation;
 */
JNIEXPORT jobject JNICALL Java_jdk_internal_jimage_RuntimeImageReader_findLocation0__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     jdk_internal_jimage_RuntimeImageReader
 * Method:    findLocation0
 * Signature: (Ljava/lang/String;)Ljdk/internal/jimage/RuntimeImageLocation;
 */
JNIEXPORT jobject JNICALL Java_jdk_internal_jimage_RuntimeImageReader_findLocation0__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jdk_internal_jimage_RuntimeImageReader
 * Method:    getResource0
 * Signature: (Ljdk/internal/jimage/RuntimeImageReader/Resource;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_jdk_internal_jimage_RuntimeImageReader_getResource0
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
