/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jdk_internal_invoke_NativeEntryPoint */

#ifndef _Included_jdk_internal_invoke_NativeEntryPoint
#define _Included_jdk_internal_invoke_NativeEntryPoint
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jdk_internal_invoke_NativeEntryPoint
 * Method:    vmStorageToVMReg
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_jdk_internal_invoke_NativeEntryPoint_vmStorageToVMReg
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     jdk_internal_invoke_NativeEntryPoint
 * Method:    registerNatives
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jdk_internal_invoke_NativeEntryPoint_registerNatives
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
