/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_nio_ch_NativeSocketAddress */

#ifndef _Included_sun_nio_ch_NativeSocketAddress
#define _Included_sun_nio_ch_NativeSocketAddress
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sun_nio_ch_NativeSocketAddress
 * Method:    AFINET
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sun_nio_ch_NativeSocketAddress_AFINET
  (JNIEnv *, jclass);

/*
 * Class:     sun_nio_ch_NativeSocketAddress
 * Method:    AFINET6
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sun_nio_ch_NativeSocketAddress_AFINET6
  (JNIEnv *, jclass);

/*
 * Class:     sun_nio_ch_NativeSocketAddress
 * Method:    sizeofSockAddr4
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sun_nio_ch_NativeSocketAddress_sizeofSockAddr4
  (JNIEnv *, jclass);

/*
 * Class:     sun_nio_ch_NativeSocketAddress
 * Method:    sizeofSockAddr6
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sun_nio_ch_NativeSocketAddress_sizeofSockAddr6
  (JNIEnv *, jclass);

/*
 * Class:     sun_nio_ch_NativeSocketAddress
 * Method:    sizeofFamily
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sun_nio_ch_NativeSocketAddress_sizeofFamily
  (JNIEnv *, jclass);

/*
 * Class:     sun_nio_ch_NativeSocketAddress
 * Method:    offsetFamily
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sun_nio_ch_NativeSocketAddress_offsetFamily
  (JNIEnv *, jclass);

/*
 * Class:     sun_nio_ch_NativeSocketAddress
 * Method:    offsetSin4Port
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sun_nio_ch_NativeSocketAddress_offsetSin4Port
  (JNIEnv *, jclass);

/*
 * Class:     sun_nio_ch_NativeSocketAddress
 * Method:    offsetSin4Addr
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sun_nio_ch_NativeSocketAddress_offsetSin4Addr
  (JNIEnv *, jclass);

/*
 * Class:     sun_nio_ch_NativeSocketAddress
 * Method:    offsetSin6Port
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sun_nio_ch_NativeSocketAddress_offsetSin6Port
  (JNIEnv *, jclass);

/*
 * Class:     sun_nio_ch_NativeSocketAddress
 * Method:    offsetSin6Addr
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sun_nio_ch_NativeSocketAddress_offsetSin6Addr
  (JNIEnv *, jclass);

/*
 * Class:     sun_nio_ch_NativeSocketAddress
 * Method:    offsetSin6ScopeId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sun_nio_ch_NativeSocketAddress_offsetSin6ScopeId
  (JNIEnv *, jclass);

/*
 * Class:     sun_nio_ch_NativeSocketAddress
 * Method:    offsetSin6FlowInfo
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sun_nio_ch_NativeSocketAddress_offsetSin6FlowInfo
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
