/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_nio_ch_UnixDomainSockets */

#ifndef _Included_sun_nio_ch_UnixDomainSockets
#define _Included_sun_nio_ch_UnixDomainSockets
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sun_nio_ch_UnixDomainSockets
 * Method:    localAddress0
 * Signature: (Ljava/io/FileDescriptor;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_sun_nio_ch_UnixDomainSockets_localAddress0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     sun_nio_ch_UnixDomainSockets
 * Method:    init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_sun_nio_ch_UnixDomainSockets_init
  (JNIEnv *, jclass);

/*
 * Class:     sun_nio_ch_UnixDomainSockets
 * Method:    socket0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sun_nio_ch_UnixDomainSockets_socket0
  (JNIEnv *, jclass);

/*
 * Class:     sun_nio_ch_UnixDomainSockets
 * Method:    bind0
 * Signature: (Ljava/io/FileDescriptor;[B)V
 */
JNIEXPORT void JNICALL Java_sun_nio_ch_UnixDomainSockets_bind0
  (JNIEnv *, jclass, jobject, jbyteArray);

/*
 * Class:     sun_nio_ch_UnixDomainSockets
 * Method:    connect0
 * Signature: (Ljava/io/FileDescriptor;[B)I
 */
JNIEXPORT jint JNICALL Java_sun_nio_ch_UnixDomainSockets_connect0
  (JNIEnv *, jclass, jobject, jbyteArray);

/*
 * Class:     sun_nio_ch_UnixDomainSockets
 * Method:    accept0
 * Signature: (Ljava/io/FileDescriptor;Ljava/io/FileDescriptor;[Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_sun_nio_ch_UnixDomainSockets_accept0
  (JNIEnv *, jclass, jobject, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
