/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_nio_ch_DatagramChannelImpl */

#ifndef _Included_sun_nio_ch_DatagramChannelImpl
#define _Included_sun_nio_ch_DatagramChannelImpl
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_nio_ch_DatagramChannelImpl_ST_UNCONNECTED
#define sun_nio_ch_DatagramChannelImpl_ST_UNCONNECTED 0L
#undef sun_nio_ch_DatagramChannelImpl_ST_CONNECTED
#define sun_nio_ch_DatagramChannelImpl_ST_CONNECTED 1L
#undef sun_nio_ch_DatagramChannelImpl_ST_CLOSING
#define sun_nio_ch_DatagramChannelImpl_ST_CLOSING 2L
#undef sun_nio_ch_DatagramChannelImpl_ST_CLOSED
#define sun_nio_ch_DatagramChannelImpl_ST_CLOSED 3L
/*
 * Class:     sun_nio_ch_DatagramChannelImpl
 * Method:    disconnect0
 * Signature: (Ljava/io/FileDescriptor;Z)V
 */
JNIEXPORT void JNICALL Java_sun_nio_ch_DatagramChannelImpl_disconnect0
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     sun_nio_ch_DatagramChannelImpl
 * Method:    receive0
 * Signature: (Ljava/io/FileDescriptor;JIJZ)I
 */
JNIEXPORT jint JNICALL Java_sun_nio_ch_DatagramChannelImpl_receive0
  (JNIEnv *, jclass, jobject, jlong, jint, jlong, jboolean);

/*
 * Class:     sun_nio_ch_DatagramChannelImpl
 * Method:    send0
 * Signature: (Ljava/io/FileDescriptor;JIJI)I
 */
JNIEXPORT jint JNICALL Java_sun_nio_ch_DatagramChannelImpl_send0
  (JNIEnv *, jclass, jobject, jlong, jint, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
