#include <sun/net/www/content-types.properties.resource.h>

namespace sun {
    namespace net {
        namespace www {

const char content$types$properties$resource$data[] =
"#sun.net.www MIME content-types table\n"
"#\n"
"# Property fields:\n"
"#\n"
"#   <description> ::= 'description' '=' <descriptive string>\n"
"#    <extensions> ::= 'file_extensions' '=' <comma-delimited list, include '.'>\n"
"#         <image> ::= 'icon' '=' <filename of icon image>\n"
"#        <action> ::= 'browser' | 'application' | 'save' | 'unknown'\n"
"#   <application> ::= 'application' '=' <command line template>\n"
"#\n"
"\n"
"#\n"
"# The \"we don't know anything about this data\" type(s).\n"
"# Used internally to mark unrecognized types.\n"
"#\n"
"content/unknown: description=Unknown Content\n"
"unknown/unknown: description=Unknown Data Type\n"
"\n"
"#\n"
"# The template we should use for temporary files when launching an application\n"
"# to view a document of given type.\n"
"#\n"
"temp.file.template: c:\\\\temp\\\\%s\n"
"\n"
"#\n"
"# The \"real\" types.\n"
"#\n"
"application/octet-stream: \\\n"
"	description=Generic Binary Stream;\\\n"
"	file_extensions=.saveme,.dump,.hqx,.arc,.obj,.lib,.bin,.exe,.zip,.gz\n"
"\n"
"application/oda: \\\n"
"	description=ODA Document;\\\n"
"	file_extensions=.oda\n"
"\n"
"application/pdf: \\\n"
"	description=Adobe PDF Format;\\\n"
"	file_extensions=.pdf\n"
"\n"
"application/postscript: \\\n"
"	description=Postscript File;\\\n"
"	file_extensions=.eps,.ai,.ps;\\\n"
"	icon=ps\n"
"\n"
"application/rtf: \\\n"
"	description=Wordpad Document;\\\n"
"	file_extensions=.rtf;\\\n"
"	action=application;\\\n"
"	application=wordpad.exe %s\n"
"\n"
"application/x-dvi: \\\n"
"	description=TeX DVI File;\\\n"
"	file_extensions=.dvi\n"
"\n"
"application/x-hdf: \\\n"
"	description=Hierarchical Data Format;\\\n"
"	file_extensions=.hdf;\\\n"
"	action=save\n"
"\n"
"application/x-latex: \\\n"
"	description=LaTeX Source;\\\n"
"	file_extensions=.latex\n"
"\n"
"application/x-netcdf: \\\n"
"	description=Unidata netCDF Data Format;\\\n"
"	file_extensions=.nc,.cdf;\\\n"
"	action=save\n"
"\n"
"application/x-tex: \\\n"
"	description=TeX Source;\\\n"
"	file_extensions=.tex\n"
"\n"
"application/x-texinfo: \\\n"
"	description=Gnu Texinfo;\\\n"
"	file_extensions=.texinfo,.texi\n"
"\n"
"application/x-troff: \\\n"
"	description=Troff Source;\\\n"
"	file_extensions=.t,.tr,.roff\n"
"\n"
"application/x-troff-man: \\\n"
"	description=Troff Manpage Source;\\\n"
"	file_extensions=.man\n"
"\n"
"application/x-troff-me: \\\n"
"	description=Troff ME Macros;\\\n"
"	file_extensions=.me\n"
"\n"
"application/x-troff-ms: \\\n"
"	description=Troff MS Macros;\\\n"
"	file_extensions=.ms\n"
"\n"
"application/x-wais-source: \\\n"
"	description=Wais Source;\\\n"
"	file_extensions=.src,.wsrc\n"
"\n"
"application/zip: \\\n"
"	description=Zip File;\\\n"
"	file_extensions=.zip;\\\n"
"	icon=zip;\\\n"
"	action=save\n"
"\n"
"application/x-bcpio: \\\n"
"	description=Old Binary CPIO Archive;\\\n"
"	file_extensions=.bcpio;\\\n"
"	action=save\n"
"\n"
"application/x-cpio: \\\n"
"	description=Unix CPIO Archive;\\\n"
"	file_extensions=.cpio;\\\n"
"	action=save\n"
"\n"
"application/x-gtar: \\\n"
"	description=Gnu Tar Archive;\\\n"
"	file_extensions=.gtar;\\\n"
"	icon=tar;\\\n"
"	action=save\n"
"\n"
"application/x-shar: \\\n"
"	description=Shell Archive;\\\n"
"	file_extensions=.sh,.shar;\\\n"
"	action=save\n"
"\n"
"application/x-sv4cpio: \\\n"
"	description=SVR4 CPIO Archive;\\\n"
"	file_extensions=.sv4cpio;\\\n"
"	action=save\n"
"\n"
"application/x-sv4crc: \\\n"
"	description=SVR4 CPIO with CRC;\\\n"
"	file_extensions=.sv4crc;\\\n"
"	action=save\n"
"\n"
"application/x-tar: \\\n"
"	description=Tar Archive;\\\n"
"	file_extensions=.tar;\\\n"
"	icon=tar;\\\n"
"	action=save\n"
"\n"
"application/x-ustar: \\\n"
"	description=US Tar Archive;\\\n"
"	file_extensions=.ustar;\\\n"
"	action=save\n"
"\n"
"audio/aac: \\\n"
"	description=Advanced Audio Coding Audio;\\\n"
"	file_extensions=.aac\n"
"\n"
"audio/basic: \\\n"
"	description=Basic Audio;\\\n"
"	file_extensions=.snd,.au;\\\n"
"	icon=audio\n"
"\n"
"audio/flac: \\\n"
"	description=Free Lossless Audio Codec Audio;\\\n"
"	file_extensions=.flac\n"
"\n"
"audio/mp4: \\\n"
"	description=MPEG-4 Audio;\\\n"
"	file_extensions=.m4a\n"
"\n"
"audio/mpeg: \\\n"
"	description=MPEG Audio;\\\n"
"	file_extensions=.mp2,.mp3\n"
"\n"
"audio/ogg: \\\n"
"	description=Ogg Audio;\\\n"
"	file_extensions=.oga,.ogg,.opus,.spx\n"
"\n"
"audio/x-aiff: \\\n"
"	description=Audio Interchange Format File;\\\n"
"	file_extensions=.aifc,.aif,.aiff;\\\n"
"	icon=aiff\n"
"\n"
"audio/x-wav: \\\n"
"	description=Wav Audio;\\\n"
"	file_extensions=.wav;\\\n"
"	icon=wav;\\\n"
"	action=application;\\\n"
"	application=mplayer.exe %s\n"
"\n"
"image/gif: \\\n"
"	description=GIF Image;\\\n"
"	file_extensions=.gif;\\\n"
"	icon=gif;\\\n"
"	action=browser\n"
"\n"
"image/ief: \\\n"
"	description=Image Exchange Format;\\\n"
"	file_extensions=.ief\n"
"\n"
"image/jpeg: \\\n"
"	description=JPEG Image;\\\n"
"	file_extensions=.jfif,.jfif-tbnl,.jpe,.jpg,.jpeg;\\\n"
"	icon=jpeg;\\\n"
"	action=browser\n"
"\n"
"image/svg+xml: \\\n"
"	description=Scalable Vector Graphics;\\\n"
"	file_extensions=.svg,.svgz\n"
"\n"
"image/tiff: \\\n"
"	description=TIFF Image;\\\n"
"	file_extensions=.tif,.tiff;\\\n"
"	icon=tiff\n"
"\n"
"image/vnd.fpx: \\\n"
"	description=FlashPix Image;\\\n"
"	file_extensions=.fpx,.fpix\n"
"\n"
"image/x-cmu-rast: \\\n"
"	description=CMU Raster Image;\\\n"
"	file_extensions=.ras\n"
"\n"
"image/x-portable-anymap: \\\n"
"	description=PBM Anymap Image;\\\n"
"	file_extensions=.pnm\n"
"\n"
"image/x-portable-bitmap: \\\n"
"	description=PBM Bitmap Image;\\\n"
"	file_extensions=.pbm\n"
"\n"
"image/x-portable-graymap: \\\n"
"	description=PBM Graymap Image;\\\n"
"	file_extensions=.pgm\n"
"\n"
"image/x-portable-pixmap: \\\n"
"	description=PBM Pixmap Image;\\\n"
"	file_extensions=.ppm\n"
"\n"
"image/x-rgb: \\\n"
"	description=RGB Image;\\\n"
"	file_extensions=.rgb\n"
"\n"
"image/x-xbitmap: \\\n"
"	description=X Bitmap Image;\\\n"
"	file_extensions=.xbm,.xpm\n"
"\n"
"image/x-xwindowdump: \\\n"
"	description=X Window Dump Image;\\\n"
"	file_extensions=.xwd\n"
"\n"
"image/png: \\\n"
"	description=PNG Image;\\\n"
"	file_extensions=.png;\\\n"
"	icon=png;\\\n"
"	action=browser\n"
"\n"
"image/bmp: \\\n"
"	description=Bitmap Image;\\\n"
"	file_extensions=.bmp;\n"
"\n"
"text/html: \\\n"
"	description=HTML Document;\\\n"
"	file_extensions=.htm,.html;\\\n"
"	icon=html\n"
"\n"
"text/plain: \\\n"
"	description=Plain Text;\\\n"
"	file_extensions=.text,.c,.cc,.c++,.h,.pl,.txt,.java,.el;\\\n"
"	icon=text;\\\n"
"	action=browser\n"
"\n"
"text/tab-separated-values: \\\n"
"	description=Tab Separated Values Text;\\\n"
"	file_extensions=.tsv\n"
"\n"
"text/x-setext: \\\n"
"	description=Structure Enhanced Text;\\\n"
"	file_extensions=.etx\n"
"\n"
"video/mp4: \\\n"
"	description=MPEG-4 Video;\\\n"
"	file_extensions=.m4v,.mp4\n"
"\n"
"video/mpeg: \\\n"
"	description=MPEG Video Clip;\\\n"
"	file_extensions=.mpg,.mpe,.mpeg;\\\n"
"	icon=mpeg\n"
"\n"
"video/ogg: \\\n"
"	description=Ogg Video;\\\n"
"	file_extensions=.ogv\n"
"\n"
"video/quicktime: \\\n"
"	description=QuickTime Video Clip;\\\n"
"	file_extensions=.mov,.qt\n"
"\n"
"video/webm: \\\n"
"	description=WebM Video;\\\n"
"	file_extensions=.webm\n"
"\n"
"application/x-troff-msvideo: \\\n"
"	description=AVI Video;\\\n"
"	file_extensions=.avi;\\\n"
"	icon=avi;\\\n"
"	action=application;\\\n"
"	application=mplayer.exe %s\n"
"\n"
"video/x-sgi-movie: \\\n"
"	description=SGI Movie;\\\n"
"	file_extensions=.movie,.mv\n"
"\n"
"message/rfc822: \\\n"
"	description=Internet Email Message;\\\n"
"	file_extensions=.mime\n"
"\n"
"application/xml: \\\n"
"	description=XML document;\\\n"
"	file_extensions=.xml\n";

int8_t* content$types$properties$resource::get(int32_t& length) {
    length = sizeof(content$types$properties$resource$data) - 1;
    return (int8_t*)content$types$properties$resource$data;
}

        } // www
    } // net
} // sun
