/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef $LL
#ifdef _WIN32
#define $LL(x) x##i64
#else
#define $LL(x) x##LL
#endif
#endif

/* Header for class java_lang_ProcessEnvironment */

#ifndef _Included_java_lang_ProcessEnvironment
#define _Included_java_lang_ProcessEnvironment
#ifdef __cplusplus
extern "C" {
#endif
#undef java_lang_ProcessEnvironment_serialVersionUID
#define java_lang_ProcessEnvironment_serialVersionUID $LL(362498820763181265)
#undef java_lang_ProcessEnvironment_DEFAULT_INITIAL_CAPACITY
#define java_lang_ProcessEnvironment_DEFAULT_INITIAL_CAPACITY 16L
#undef java_lang_ProcessEnvironment_MAXIMUM_CAPACITY
#define java_lang_ProcessEnvironment_MAXIMUM_CAPACITY 1073741824L
#undef java_lang_ProcessEnvironment_DEFAULT_LOAD_FACTOR
#define java_lang_ProcessEnvironment_DEFAULT_LOAD_FACTOR 0.75f
#undef java_lang_ProcessEnvironment_TREEIFY_THRESHOLD
#define java_lang_ProcessEnvironment_TREEIFY_THRESHOLD 8L
#undef java_lang_ProcessEnvironment_UNTREEIFY_THRESHOLD
#define java_lang_ProcessEnvironment_UNTREEIFY_THRESHOLD 6L
#undef java_lang_ProcessEnvironment_MIN_TREEIFY_CAPACITY
#define java_lang_ProcessEnvironment_MIN_TREEIFY_CAPACITY 64L
#undef java_lang_ProcessEnvironment_serialVersionUID
#define java_lang_ProcessEnvironment_serialVersionUID $LL(-8017839552603542824)
#undef java_lang_ProcessEnvironment_MIN_NAME_LENGTH
#define java_lang_ProcessEnvironment_MIN_NAME_LENGTH 1L
/*
 * Class:     java_lang_ProcessEnvironment
 * Method:    environmentBlock
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_java_lang_ProcessEnvironment_environmentBlock
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
