/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_net_TwoStacksPlainDatagramSocketImpl */

#ifndef _Included_java_net_TwoStacksPlainDatagramSocketImpl
#define _Included_java_net_TwoStacksPlainDatagramSocketImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_net_TwoStacksPlainDatagramSocketImpl
 * Method:    bind0
 * Signature: (ILjava/net/InetAddress;Z)V
 */
JNIEXPORT void JNICALL Java_java_net_TwoStacksPlainDatagramSocketImpl_bind0
  (JNIEnv *, jobject, jint, jobject, jboolean);

/*
 * Class:     java_net_TwoStacksPlainDatagramSocketImpl
 * Method:    send0
 * Signature: (Ljava/net/DatagramPacket;)V
 */
JNIEXPORT void JNICALL Java_java_net_TwoStacksPlainDatagramSocketImpl_send0
  (JNIEnv *, jobject, jobject);

/*
 * Class:     java_net_TwoStacksPlainDatagramSocketImpl
 * Method:    peek
 * Signature: (Ljava/net/InetAddress;)I
 */
JNIEXPORT jint JNICALL Java_java_net_TwoStacksPlainDatagramSocketImpl_peek
  (JNIEnv *, jobject, jobject);

/*
 * Class:     java_net_TwoStacksPlainDatagramSocketImpl
 * Method:    peekData
 * Signature: (Ljava/net/DatagramPacket;)I
 */
JNIEXPORT jint JNICALL Java_java_net_TwoStacksPlainDatagramSocketImpl_peekData
  (JNIEnv *, jobject, jobject);

/*
 * Class:     java_net_TwoStacksPlainDatagramSocketImpl
 * Method:    receive0
 * Signature: (Ljava/net/DatagramPacket;)V
 */
JNIEXPORT void JNICALL Java_java_net_TwoStacksPlainDatagramSocketImpl_receive0
  (JNIEnv *, jobject, jobject);

/*
 * Class:     java_net_TwoStacksPlainDatagramSocketImpl
 * Method:    setTimeToLive
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_java_net_TwoStacksPlainDatagramSocketImpl_setTimeToLive
  (JNIEnv *, jobject, jint);

/*
 * Class:     java_net_TwoStacksPlainDatagramSocketImpl
 * Method:    getTimeToLive
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_java_net_TwoStacksPlainDatagramSocketImpl_getTimeToLive
  (JNIEnv *, jobject);

/*
 * Class:     java_net_TwoStacksPlainDatagramSocketImpl
 * Method:    setTTL
 * Signature: (B)V
 */
JNIEXPORT void JNICALL Java_java_net_TwoStacksPlainDatagramSocketImpl_setTTL
  (JNIEnv *, jobject, jbyte);

/*
 * Class:     java_net_TwoStacksPlainDatagramSocketImpl
 * Method:    getTTL
 * Signature: ()B
 */
JNIEXPORT jbyte JNICALL Java_java_net_TwoStacksPlainDatagramSocketImpl_getTTL
  (JNIEnv *, jobject);

/*
 * Class:     java_net_TwoStacksPlainDatagramSocketImpl
 * Method:    join
 * Signature: (Ljava/net/InetAddress;Ljava/net/NetworkInterface;)V
 */
JNIEXPORT void JNICALL Java_java_net_TwoStacksPlainDatagramSocketImpl_join
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     java_net_TwoStacksPlainDatagramSocketImpl
 * Method:    leave
 * Signature: (Ljava/net/InetAddress;Ljava/net/NetworkInterface;)V
 */
JNIEXPORT void JNICALL Java_java_net_TwoStacksPlainDatagramSocketImpl_leave
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     java_net_TwoStacksPlainDatagramSocketImpl
 * Method:    datagramSocketCreate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_java_net_TwoStacksPlainDatagramSocketImpl_datagramSocketCreate
  (JNIEnv *, jobject);

/*
 * Class:     java_net_TwoStacksPlainDatagramSocketImpl
 * Method:    datagramSocketClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_java_net_TwoStacksPlainDatagramSocketImpl_datagramSocketClose
  (JNIEnv *, jobject);

/*
 * Class:     java_net_TwoStacksPlainDatagramSocketImpl
 * Method:    socketNativeSetOption
 * Signature: (ILjava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_java_net_TwoStacksPlainDatagramSocketImpl_socketNativeSetOption
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     java_net_TwoStacksPlainDatagramSocketImpl
 * Method:    socketGetOption
 * Signature: (I)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_java_net_TwoStacksPlainDatagramSocketImpl_socketGetOption
  (JNIEnv *, jobject, jint);

/*
 * Class:     java_net_TwoStacksPlainDatagramSocketImpl
 * Method:    connect0
 * Signature: (Ljava/net/InetAddress;I)V
 */
JNIEXPORT void JNICALL Java_java_net_TwoStacksPlainDatagramSocketImpl_connect0
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     java_net_TwoStacksPlainDatagramSocketImpl
 * Method:    socketLocalAddress
 * Signature: (I)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_java_net_TwoStacksPlainDatagramSocketImpl_socketLocalAddress
  (JNIEnv *, jobject, jint);

/*
 * Class:     java_net_TwoStacksPlainDatagramSocketImpl
 * Method:    disconnect0
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_java_net_TwoStacksPlainDatagramSocketImpl_disconnect0
  (JNIEnv *, jobject, jint);

/*
 * Class:     java_net_TwoStacksPlainDatagramSocketImpl
 * Method:    dataAvailable
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_java_net_TwoStacksPlainDatagramSocketImpl_dataAvailable
  (JNIEnv *, jobject);

/*
 * Class:     java_net_TwoStacksPlainDatagramSocketImpl
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_java_net_TwoStacksPlainDatagramSocketImpl_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
