/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_nio_ch_WindowsSelectorImpl_SubSelector */

#ifndef _Included_sun_nio_ch_WindowsSelectorImpl_SubSelector
#define _Included_sun_nio_ch_WindowsSelectorImpl_SubSelector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sun_nio_ch_WindowsSelectorImpl_SubSelector
 * Method:    poll0
 * Signature: (JI[I[I[IJJ)I
 */
JNIEXPORT jint JNICALL Java_sun_nio_ch_WindowsSelectorImpl_00024SubSelector_poll0
  (JNIEnv *, jobject, jlong, jint, jintArray, jintArray, jintArray, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
