/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef $LL
#ifdef _WIN32
#define $LL(x) x##i64
#else
#define $LL(x) x##LL
#endif
#endif

/* Header for class sun_io_Win32ErrorMode */

#ifndef _Included_sun_io_Win32ErrorMode
#define _Included_sun_io_Win32ErrorMode
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_io_Win32ErrorMode_SEM_FAILCRITICALERRORS
#define sun_io_Win32ErrorMode_SEM_FAILCRITICALERRORS $LL(1)
#undef sun_io_Win32ErrorMode_SEM_NOGPFAULTERRORBOX
#define sun_io_Win32ErrorMode_SEM_NOGPFAULTERRORBOX $LL(2)
#undef sun_io_Win32ErrorMode_SEM_NOALIGNMENTFAULTEXCEPT
#define sun_io_Win32ErrorMode_SEM_NOALIGNMENTFAULTEXCEPT $LL(4)
#undef sun_io_Win32ErrorMode_SEM_NOOPENFILEERRORBOX
#define sun_io_Win32ErrorMode_SEM_NOOPENFILEERRORBOX $LL(32768)
/*
 * Class:     sun_io_Win32ErrorMode
 * Method:    setErrorMode
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_sun_io_Win32ErrorMode_setErrorMode
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
