/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_nio_ch_WEPoll */

#ifndef _Included_sun_nio_ch_WEPoll
#define _Included_sun_nio_ch_WEPoll
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_nio_ch_WEPoll_EPOLL_CTL_ADD
#define sun_nio_ch_WEPoll_EPOLL_CTL_ADD 1L
#undef sun_nio_ch_WEPoll_EPOLL_CTL_MOD
#define sun_nio_ch_WEPoll_EPOLL_CTL_MOD 2L
#undef sun_nio_ch_WEPoll_EPOLL_CTL_DEL
#define sun_nio_ch_WEPoll_EPOLL_CTL_DEL 3L
#undef sun_nio_ch_WEPoll_EPOLLIN
#define sun_nio_ch_WEPoll_EPOLLIN 1L
#undef sun_nio_ch_WEPoll_EPOLLPRI
#define sun_nio_ch_WEPoll_EPOLLPRI 2L
#undef sun_nio_ch_WEPoll_EPOLLOUT
#define sun_nio_ch_WEPoll_EPOLLOUT 4L
#undef sun_nio_ch_WEPoll_EPOLLERR
#define sun_nio_ch_WEPoll_EPOLLERR 8L
#undef sun_nio_ch_WEPoll_EPOLLHUP
#define sun_nio_ch_WEPoll_EPOLLHUP 16L
#undef sun_nio_ch_WEPoll_EPOLLONESHOT
#define sun_nio_ch_WEPoll_EPOLLONESHOT -2147483648L
/*
 * Class:     sun_nio_ch_WEPoll
 * Method:    eventSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sun_nio_ch_WEPoll_eventSize
  (JNIEnv *, jclass);

/*
 * Class:     sun_nio_ch_WEPoll
 * Method:    eventsOffset
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sun_nio_ch_WEPoll_eventsOffset
  (JNIEnv *, jclass);

/*
 * Class:     sun_nio_ch_WEPoll
 * Method:    dataOffset
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sun_nio_ch_WEPoll_dataOffset
  (JNIEnv *, jclass);

/*
 * Class:     sun_nio_ch_WEPoll
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_sun_nio_ch_WEPoll_create
  (JNIEnv *, jclass);

/*
 * Class:     sun_nio_ch_WEPoll
 * Method:    ctl
 * Signature: (JIJI)I
 */
JNIEXPORT jint JNICALL Java_sun_nio_ch_WEPoll_ctl
  (JNIEnv *, jclass, jlong, jint, jlong, jint);

/*
 * Class:     sun_nio_ch_WEPoll
 * Method:    wait
 * Signature: (JJII)I
 */
JNIEXPORT jint JNICALL Java_sun_nio_ch_WEPoll_wait
  (JNIEnv *, jclass, jlong, jlong, jint, jint);

/*
 * Class:     sun_nio_ch_WEPoll
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_sun_nio_ch_WEPoll_close
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
