/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef $LL
#ifdef _WIN32
#define $LL(x) x##i64
#else
#define $LL(x) x##LL
#endif
#endif

/* Header for class sun_net_www_protocol_http_ntlm_NTLMAuthentication */

#ifndef _Included_sun_net_www_protocol_http_ntlm_NTLMAuthentication
#define _Included_sun_net_www_protocol_http_ntlm_NTLMAuthentication
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_net_www_protocol_http_ntlm_NTLMAuthentication_serialVersionUID
#define sun_net_www_protocol_http_ntlm_NTLMAuthentication_serialVersionUID $LL(735249334068211611)
#undef sun_net_www_protocol_http_ntlm_NTLMAuthentication_serialVersionUID
#define sun_net_www_protocol_http_ntlm_NTLMAuthentication_serialVersionUID $LL(-2588378268010453259)
#undef sun_net_www_protocol_http_ntlm_NTLMAuthentication_SERVER_AUTHENTICATION
#define sun_net_www_protocol_http_ntlm_NTLMAuthentication_SERVER_AUTHENTICATION 115L
#undef sun_net_www_protocol_http_ntlm_NTLMAuthentication_PROXY_AUTHENTICATION
#define sun_net_www_protocol_http_ntlm_NTLMAuthentication_PROXY_AUTHENTICATION 112L
#undef sun_net_www_protocol_http_ntlm_NTLMAuthentication_serialVersionUID
#define sun_net_www_protocol_http_ntlm_NTLMAuthentication_serialVersionUID $LL(100)
/*
 * Class:     sun_net_www_protocol_http_ntlm_NTLMAuthentication
 * Method:    isTrustedSiteAvailable
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_sun_net_www_protocol_http_ntlm_NTLMAuthentication_isTrustedSiteAvailable
  (JNIEnv *, jclass);

/*
 * Class:     sun_net_www_protocol_http_ntlm_NTLMAuthentication
 * Method:    isTrustedSite0
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_sun_net_www_protocol_http_ntlm_NTLMAuthentication_isTrustedSite0
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
