/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_nio_ch_PollArrayWrapper */

#ifndef _Included_sun_nio_ch_PollArrayWrapper
#define _Included_sun_nio_ch_PollArrayWrapper
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_nio_ch_PollArrayWrapper_FD_OFFSET
#define sun_nio_ch_PollArrayWrapper_FD_OFFSET 0L
#undef sun_nio_ch_PollArrayWrapper_EVENT_OFFSET
#define sun_nio_ch_PollArrayWrapper_EVENT_OFFSET 4L
#ifdef __cplusplus
}
#endif
#endif
