/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef $LL
#ifdef _WIN32
#define $LL(x) x##i64
#else
#define $LL(x) x##LL
#endif
#endif

/* Header for class sun_nio_ch_Iocp */

#ifndef _Included_sun_nio_ch_Iocp
#define _Included_sun_nio_ch_Iocp
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_nio_ch_Iocp_INVALID_HANDLE_VALUE
#define sun_nio_ch_Iocp_INVALID_HANDLE_VALUE $LL(-1)
/*
 * Class:     sun_nio_ch_Iocp
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_nio_ch_Iocp_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     sun_nio_ch_Iocp
 * Method:    createIoCompletionPort
 * Signature: (JJII)J
 */
JNIEXPORT jlong JNICALL Java_sun_nio_ch_Iocp_createIoCompletionPort
  (JNIEnv *, jclass, jlong, jlong, jint, jint);

/*
 * Class:     sun_nio_ch_Iocp
 * Method:    close0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_sun_nio_ch_Iocp_close0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     sun_nio_ch_Iocp
 * Method:    getQueuedCompletionStatus
 * Signature: (JLsun/nio/ch/Iocp/CompletionStatus;)V
 */
JNIEXPORT void JNICALL Java_sun_nio_ch_Iocp_getQueuedCompletionStatus
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     sun_nio_ch_Iocp
 * Method:    postQueuedCompletionStatus
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_sun_nio_ch_Iocp_postQueuedCompletionStatus
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     sun_nio_ch_Iocp
 * Method:    getErrorMessage
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_sun_nio_ch_Iocp_getErrorMessage
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
