/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_nio_ch_WindowsSelectorImpl */

#ifndef _Included_sun_nio_ch_WindowsSelectorImpl
#define _Included_sun_nio_ch_WindowsSelectorImpl
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_nio_ch_WindowsSelectorImpl_MAX_SELECTABLE_FDS
#define sun_nio_ch_WindowsSelectorImpl_MAX_SELECTABLE_FDS 1024L
/*
 * Class:     sun_nio_ch_WindowsSelectorImpl
 * Method:    setWakeupSocket0
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_sun_nio_ch_WindowsSelectorImpl_setWakeupSocket0
  (JNIEnv *, jobject, jint);

/*
 * Class:     sun_nio_ch_WindowsSelectorImpl
 * Method:    resetWakeupSocket0
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_sun_nio_ch_WindowsSelectorImpl_resetWakeupSocket0
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
