/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_nio_fs_RegistryFileTypeDetector */

#ifndef _Included_sun_nio_fs_RegistryFileTypeDetector
#define _Included_sun_nio_fs_RegistryFileTypeDetector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sun_nio_fs_RegistryFileTypeDetector
 * Method:    queryStringValue
 * Signature: (JJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_sun_nio_fs_RegistryFileTypeDetector_queryStringValue
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
