/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_nio_ch_SocketDispatcher */

#ifndef _Included_sun_nio_ch_SocketDispatcher
#define _Included_sun_nio_ch_SocketDispatcher
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sun_nio_ch_SocketDispatcher
 * Method:    read0
 * Signature: (Ljava/io/FileDescriptor;JI)I
 */
JNIEXPORT jint JNICALL Java_sun_nio_ch_SocketDispatcher_read0
  (JNIEnv *, jclass, jobject, jlong, jint);

/*
 * Class:     sun_nio_ch_SocketDispatcher
 * Method:    readv0
 * Signature: (Ljava/io/FileDescriptor;JI)J
 */
JNIEXPORT jlong JNICALL Java_sun_nio_ch_SocketDispatcher_readv0
  (JNIEnv *, jclass, jobject, jlong, jint);

/*
 * Class:     sun_nio_ch_SocketDispatcher
 * Method:    write0
 * Signature: (Ljava/io/FileDescriptor;JI)I
 */
JNIEXPORT jint JNICALL Java_sun_nio_ch_SocketDispatcher_write0
  (JNIEnv *, jclass, jobject, jlong, jint);

/*
 * Class:     sun_nio_ch_SocketDispatcher
 * Method:    writev0
 * Signature: (Ljava/io/FileDescriptor;JI)J
 */
JNIEXPORT jlong JNICALL Java_sun_nio_ch_SocketDispatcher_writev0
  (JNIEnv *, jclass, jobject, jlong, jint);

/*
 * Class:     sun_nio_ch_SocketDispatcher
 * Method:    close0
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_sun_nio_ch_SocketDispatcher_close0
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
