/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_security_provider_NativeSeedGenerator */

#ifndef _Included_sun_security_provider_NativeSeedGenerator
#define _Included_sun_security_provider_NativeSeedGenerator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sun_security_provider_NativeSeedGenerator
 * Method:    nativeGenerateSeed
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_sun_security_provider_NativeSeedGenerator_nativeGenerateSeed
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
