/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_net_www_protocol_http_ntlm_NTLMAuthSequence */

#ifndef _Included_sun_net_www_protocol_http_ntlm_NTLMAuthSequence
#define _Included_sun_net_www_protocol_http_ntlm_NTLMAuthSequence
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sun_net_www_protocol_http_ntlm_NTLMAuthSequence
 * Method:    initFirst
 * Signature: (Ljava/lang/Class;)V
 */
JNIEXPORT void JNICALL Java_sun_net_www_protocol_http_ntlm_NTLMAuthSequence_initFirst
  (JNIEnv *, jclass, jclass);

/*
 * Class:     sun_net_www_protocol_http_ntlm_NTLMAuthSequence
 * Method:    getCredentialsHandle
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_sun_net_www_protocol_http_ntlm_NTLMAuthSequence_getCredentialsHandle
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     sun_net_www_protocol_http_ntlm_NTLMAuthSequence
 * Method:    getNextToken
 * Signature: (J[BLsun/net/www/protocol/http/ntlm/NTLMAuthSequence/Status;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_sun_net_www_protocol_http_ntlm_NTLMAuthSequence_getNextToken
  (JNIEnv *, jobject, jlong, jbyteArray, jobject);

#ifdef __cplusplus
}
#endif
#endif
