/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_net_dns_ResolverConfigurationImpl */

#ifndef _Included_sun_net_dns_ResolverConfigurationImpl
#define _Included_sun_net_dns_ResolverConfigurationImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sun_net_dns_ResolverConfigurationImpl
 * Method:    init0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_net_dns_ResolverConfigurationImpl_init0
  (JNIEnv *, jclass);

/*
 * Class:     sun_net_dns_ResolverConfigurationImpl
 * Method:    loadDNSconfig0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_net_dns_ResolverConfigurationImpl_loadDNSconfig0
  (JNIEnv *, jclass);

/*
 * Class:     sun_net_dns_ResolverConfigurationImpl
 * Method:    notifyAddrChange0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sun_net_dns_ResolverConfigurationImpl_notifyAddrChange0
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
