/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class p_Test */

#ifndef _Included_p_Test
#define _Included_p_Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     p_Test
 * Method:    count
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_p_Test_count
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
