/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class StringPlatformChars */

#ifndef _Included_StringPlatformChars
#define _Included_StringPlatformChars
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     StringPlatformChars
 * Method:    getBytes
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_StringPlatformChars_getBytes
  (JNIEnv *, jclass, jstring);

/*
 * Class:     StringPlatformChars
 * Method:    newString
 * Signature: ([B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_StringPlatformChars_newString
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
