//$ module java.base
::java::lang::RequiresDirective _java$base_ModuleInfo_Requires_[] = {
    {}
};

::java::lang::ExportsDirective _java$base_ModuleInfo_Exports_[] = {
    {"java.io", nullptr},
    {"java.lang", nullptr},
    {"java.lang.annotation", nullptr},
    {"java.lang.constant", nullptr},
    {"java.lang.invoke", nullptr},
    {"java.lang.module", nullptr},
    {"java.lang.ref", nullptr},
    {"java.lang.reflect", nullptr},
    {"java.lang.runtime", nullptr},
    {"java.math", nullptr},
    {"java.net", nullptr},
    {"java.net.spi", nullptr},
    {"java.nio", nullptr},
    {"java.nio.channels", nullptr},
    {"java.nio.channels.spi", nullptr},
    {"java.nio.charset", nullptr},
    {"java.nio.charset.spi", nullptr},
    {"java.nio.file", nullptr},
    {"java.nio.file.attribute", nullptr},
    {"java.nio.file.spi", nullptr},
    {"java.security", nullptr},
    {"java.security.cert", nullptr},
    {"java.security.interfaces", nullptr},
    {"java.security.spec", nullptr},
    {"java.text", nullptr},
    {"java.text.spi", nullptr},
    {"java.time", nullptr},
    {"java.time.chrono", nullptr},
    {"java.time.format", nullptr},
    {"java.time.temporal", nullptr},
    {"java.time.zone", nullptr},
    {"java.util", nullptr},
    {"java.util.concurrent", nullptr},
    {"java.util.concurrent.atomic", nullptr},
    {"java.util.concurrent.locks", nullptr},
    {"java.util.function", nullptr},
    {"java.util.jar", nullptr},
    {"java.util.random", nullptr},
    {"java.util.regex", nullptr},
    {"java.util.spi", nullptr},
    {"java.util.stream", nullptr},
    {"java.util.zip", nullptr},
    {"javax.crypto", nullptr},
    {"javax.crypto.interfaces", nullptr},
    {"javax.crypto.spec", nullptr},
    {"javax.net", nullptr},
    {"javax.net.ssl", nullptr},
    {"javax.security.auth", nullptr},
    {"javax.security.auth.callback", nullptr},
    {"javax.security.auth.login", nullptr},
    {"javax.security.auth.spi", nullptr},
    {"javax.security.auth.x500", nullptr},
    {"javax.security.cert", nullptr},
    {"com.sun.crypto.provider", "jdk.crypto.cryptoki"},
    {"com.sun.security.ntlm", "java.security.sasl"},
    {"jdk.internal.access", "java.desktop,java.logging,java.management,java.naming,java.rmi,jdk.incubator.foreign,jdk.jartool,jdk.jlink,jdk.net"},
    {"jdk.internal.access.foreign", "jdk.incubator.foreign"},
    {"jdk.internal.event", "jdk.jfr"},
    {"jdk.internal.invoke", "jdk.incubator.foreign"},
    {"jdk.internal.javac", "java.compiler,jdk.compiler,jdk.jshell"},
    {"jdk.internal.jimage", "jdk.jlink"},
    {"jdk.internal.jimage.decompressor", "jdk.jlink"},
    {"jdk.internal.jmod", "jdk.compiler,jdk.jlink"},
    {"jdk.internal.loader", "java.instrument,java.logging,java.naming,jdk.incubator.foreign"},
    {"jdk.internal.logger", "java.logging"},
    {"jdk.internal.misc", "java.desktop,java.logging,java.management,java.naming,java.net.http,java.rmi,java.security.jgss,jdk.attach,jdk.charsets,jdk.compiler,jdk.crypto.cryptoki,jdk.incubator.foreign,jdk.incubator.vector,jdk.internal.vm.ci,jdk.jfr,jdk.jshell,jdk.nio.mapmode,jdk.unsupported"},
    {"jdk.internal.module", "java.instrument,java.management.rmi,jdk.incubator.foreign,jdk.jartool,jdk.jfr,jdk.jlink,jdk.jpackage"},
    {"jdk.internal.org.objectweb.asm", "jdk.jartool,jdk.jfr,jdk.jlink"},
    {"jdk.internal.org.objectweb.asm.commons", "jdk.jfr"},
    {"jdk.internal.org.objectweb.asm.tree", "jdk.jfr,jdk.jlink"},
    {"jdk.internal.org.objectweb.asm.util", "jdk.jfr"},
    {"jdk.internal.org.xml.sax", "jdk.jfr"},
    {"jdk.internal.org.xml.sax.helpers", "jdk.jfr"},
    {"jdk.internal.perf", "java.management,jdk.internal.jvmstat,jdk.management.agent"},
    {"jdk.internal.platform", "jdk.jfr,jdk.management"},
    {"jdk.internal.ref", "java.desktop,jdk.incubator.foreign"},
    {"jdk.internal.reflect", "java.logging,java.sql,java.sql.rowset,jdk.dynalink,jdk.incubator.foreign,jdk.internal.vm.ci,jdk.unsupported"},
    {"jdk.internal.util", "jdk.incubator.foreign"},
    {"jdk.internal.util.jar", "jdk.jartool"},
    {"jdk.internal.util.random", "jdk.random"},
    {"jdk.internal.util.xml", "jdk.jfr"},
    {"jdk.internal.util.xml.impl", "jdk.jfr"},
    {"jdk.internal.vm", "jdk.internal.jvmstat,jdk.management.agent"},
    {"jdk.internal.vm.annotation", "java.instrument,jdk.incubator.foreign,jdk.incubator.vector,jdk.internal.vm.ci,jdk.jfr,jdk.unsupported"},
    {"jdk.internal.vm.vector", "jdk.incubator.vector"},
    {"sun.invoke.util", "jdk.compiler,jdk.incubator.foreign"},
    {"sun.net", "java.net.http,jdk.naming.dns"},
    {"sun.net.dns", "java.security.jgss,jdk.naming.dns"},
    {"sun.net.ext", "jdk.net"},
    {"sun.net.util", "java.desktop,java.net.http,jdk.jconsole,jdk.sctp"},
    {"sun.net.www", "java.net.http,jdk.jartool"},
    {"sun.net.www.protocol.http", "java.security.jgss"},
    {"sun.nio.ch", "java.management,jdk.crypto.cryptoki,jdk.incubator.foreign,jdk.net,jdk.sctp"},
    {"sun.nio.cs", "jdk.charsets"},
    {"sun.nio.fs", "jdk.net"},
    {"sun.reflect.annotation", "jdk.compiler"},
    {"sun.reflect.generics.reflectiveObjects", "java.desktop"},
    {"sun.reflect.misc", "java.datatransfer,java.desktop,java.management,java.management.rmi,java.rmi,java.sql.rowset"},
    {"sun.security.action", "java.desktop,java.security.jgss,jdk.crypto.ec,jdk.incubator.foreign"},
    {"sun.security.internal.interfaces", "jdk.crypto.cryptoki"},
    {"sun.security.internal.spec", "jdk.crypto.cryptoki,jdk.crypto.mscapi"},
    {"sun.security.jca", "java.smartcardio,jdk.crypto.cryptoki,jdk.crypto.ec,jdk.naming.dns"},
    {"sun.security.pkcs", "jdk.crypto.ec,jdk.jartool"},
    {"sun.security.provider", "java.rmi,java.security.jgss,jdk.crypto.cryptoki,jdk.crypto.ec,jdk.security.auth"},
    {"sun.security.provider.certpath", "java.naming"},
    {"sun.security.rsa", "jdk.crypto.cryptoki,jdk.crypto.mscapi"},
    {"sun.security.timestamp", "jdk.jartool"},
    {"sun.security.tools", "jdk.jartool"},
    {"sun.security.util", "java.desktop,java.naming,java.rmi,java.security.jgss,java.security.sasl,java.smartcardio,java.xml.crypto,jdk.crypto.cryptoki,jdk.crypto.ec,jdk.crypto.mscapi,jdk.jartool,jdk.security.auth,jdk.security.jgss"},
    {"sun.security.util.math", "jdk.crypto.ec"},
    {"sun.security.util.math.intpoly", "jdk.crypto.ec"},
    {"sun.security.validator", "jdk.jartool"},
    {"sun.security.x509", "jdk.crypto.cryptoki,jdk.crypto.ec,jdk.jartool"},
    {"sun.util.cldr", "jdk.jlink"},
    {"sun.util.locale.provider", "java.desktop,jdk.jlink,jdk.localedata"},
    {"sun.util.logging", "java.desktop,java.logging,java.prefs"},
    {"sun.util.resources", "jdk.localedata"},
    {"sun.reflect.generics.tree", nullptr},
    {"sun.net.www.protocol.jar", nullptr},
    {"jdk.internal.math", nullptr},
    {"sun.util.calendar", nullptr},
    {"jdk.internal.icu.text", nullptr},
    {"sun.invoke", nullptr},
    {"sun.text", nullptr},
    {"sun.reflect.generics.parser", nullptr},
    {"sun.net.www.protocol.ftp", nullptr},
    {}
};

::java::lang::OpensDirective _java$base_ModuleInfo_Opens_[] = {
    {}
};

::java::lang::UsesDirective _java$base_ModuleInfo_Uses_[] = {
    {"java.lang.System$LoggerFinder"},
    {"java.net.ContentHandlerFactory"},
    {"java.net.spi.URLStreamHandlerProvider"},
    {"java.nio.channels.spi.AsynchronousChannelProvider"},
    {"java.nio.channels.spi.SelectorProvider"},
    {"java.nio.charset.spi.CharsetProvider"},
    {"java.nio.file.spi.FileSystemProvider"},
    {"java.nio.file.spi.FileTypeDetector"},
    {"java.security.Provider"},
    {"java.text.spi.BreakIteratorProvider"},
    {"java.text.spi.CollatorProvider"},
    {"java.text.spi.DateFormatProvider"},
    {"java.text.spi.DateFormatSymbolsProvider"},
    {"java.text.spi.DecimalFormatSymbolsProvider"},
    {"java.text.spi.NumberFormatProvider"},
    {"java.time.chrono.AbstractChronology"},
    {"java.time.chrono.Chronology"},
    {"java.time.zone.ZoneRulesProvider"},
    {"java.util.random.RandomGenerator"},
    {"java.util.spi.CalendarDataProvider"},
    {"java.util.spi.CalendarNameProvider"},
    {"java.util.spi.CurrencyNameProvider"},
    {"java.util.spi.LocaleNameProvider"},
    {"java.util.spi.ResourceBundleControlProvider"},
    {"java.util.spi.ResourceBundleProvider"},
    {"java.util.spi.TimeZoneNameProvider"},
    {"java.util.spi.ToolProvider"},
    {"javax.security.auth.spi.LoginModule"},
    {"jdk.internal.logger.DefaultLoggerFinder"},
    {"sun.text.spi.JavaTimeDateTimePatternProvider"},
    {"sun.util.locale.provider.LocaleDataMetaInfo"},
    {"sun.util.resources.LocaleData$CommonResourceBundleProvider"},
    {"sun.util.resources.LocaleData$SupplementaryResourceBundleProvider"},
    {"sun.util.spi.CalendarProvider"},
    {}
};

::java::lang::ProvidesDirective _java$base_ModuleInfo_Provides_[] = {
    {"java.nio.file.spi.FileSystemProvider", "jdk.internal.jrtfs.JrtFileSystemProvider"},
    {"java.util.random.RandomGenerator", "java.security.SecureRandom,java.util.Random,java.util.SplittableRandom"},
    {}
};

::java::lang::ModuleInfo _java$base_ModuleInfo_ = {
    "java.base",
    false,
    _java$base_ModuleInfo_Requires_,
    _java$base_ModuleInfo_Exports_,
    _java$base_ModuleInfo_Opens_,
    _java$base_ModuleInfo_Uses_,
    _java$base_ModuleInfo_Provides_
};