/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jdk_internal_platform_CgroupMetrics */

#ifndef _Included_jdk_internal_platform_CgroupMetrics
#define _Included_jdk_internal_platform_CgroupMetrics
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jdk_internal_platform_CgroupMetrics
 * Method:    isUseContainerSupport
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jdk_internal_platform_CgroupMetrics_isUseContainerSupport
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
