/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_nio_ch_EventFD */

#ifndef _Included_sun_nio_ch_EventFD
#define _Included_sun_nio_ch_EventFD
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sun_nio_ch_EventFD
 * Method:    eventfd0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sun_nio_ch_EventFD_eventfd0
  (JNIEnv *, jclass);

/*
 * Class:     sun_nio_ch_EventFD
 * Method:    set0
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_sun_nio_ch_EventFD_set0
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
